CREATE TABLE "genshin_t3_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "genshin_t3_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "genshin_t3_artifact_itself" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "genshin_t3_artifact_itself_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"set" varchar(255),
	"type" varchar(50),
	"mainStat" varchar(50),
	"numberOfSubstat" integer,
	"percentATK" integer DEFAULT 0,
	"percentHP" integer DEFAULT 0,
	"percentDEF" integer DEFAULT 0,
	"atk" integer DEFAULT 0,
	"hp" integer DEFAULT 0,
	"def" integer DEFAULT 0,
	"er" integer DEFAULT 0,
	"em" integer DEFAULT 0,
	"critRate" integer DEFAULT 0,
	"critDMG" integer DEFAULT 0,
	"whereGotIt" varchar(50),
	"score" varchar(50),
	"unactivatedSubstat" varchar(50),
	"createDate" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "genshin_t3_artifact_leveling" (
	"id" integer PRIMARY KEY NOT NULL,
	"lHP" integer DEFAULT 0,
	"lATK" integer DEFAULT 0,
	"lDEF" integer DEFAULT 0,
	"lPercentHP" integer DEFAULT 0,
	"lPercentATK" integer DEFAULT 0,
	"lPercentDEF" integer DEFAULT 0,
	"lEM" integer DEFAULT 0,
	"lER" integer DEFAULT 0,
	"lCritRate" integer DEFAULT 0,
	"lCritDMG" integer DEFAULT 0,
	"addedSubstat" varchar(20) DEFAULT 'None',
	"createDate" timestamp NOT NULL,
	"lastAdded" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "genshin_t3_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "genshin_t3_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "genshin_t3_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "genshin_t3_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "genshin_t3_account" ADD CONSTRAINT "genshin_t3_account_userId_genshin_t3_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."genshin_t3_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "genshin_t3_artifact_itself" ADD CONSTRAINT "genshin_t3_artifact_itself_userId_genshin_t3_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."genshin_t3_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "genshin_t3_artifact_leveling" ADD CONSTRAINT "genshin_t3_artifact_leveling_id_genshin_t3_artifact_itself_id_fk" FOREIGN KEY ("id") REFERENCES "public"."genshin_t3_artifact_itself"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "genshin_t3_session" ADD CONSTRAINT "genshin_t3_session_userId_genshin_t3_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."genshin_t3_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "genshin_t3_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "artifact_user_id_idx" ON "genshin_t3_artifact_itself" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "artifact_set_idx" ON "genshin_t3_artifact_itself" USING btree ("set");--> statement-breakpoint
CREATE INDEX "artifact_leveling_id_idx" ON "genshin_t3_artifact_leveling" USING btree ("id");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "genshin_t3_session" USING btree ("userId");