const apiConfig = {
    apiUrl: 'http://localhost:8000',
  };
  
  const artifactConfig = {
    artifactTypes: [
        { value: "Flower", label: "Flower" },
        { value: "Plume", label: "Plume" },
        { value: "Sand", label: "Sand" },
        { value: "Goblet", label: "Goblet" },
        { value: "Circlet", label: "Circlet" },
    ],
    mainStatsOptions: {
        Flower: [{ value: "HP", label: "HP" }],
        Plume: [{ value: "ATK", label: "ATK" }],
        Sand: [
            { value: "%HP", label: "%HP" },
            { value: "%ATK", label: "%ATK" },
            { value: "%DEF", label: "%DEF" },
            { value: "ER", label: "ER" },
            { value: "EM", label: "EM" },
        ],
        Goblet: [
            { value: "%HP", label: "%HP" },
            { value: "%ATK", label: "%ATK" },
            { value: "%DEF", label: "%DEF" },
            { value: "EM", label: "EM" },
            { value: "Physical", label: "Physical" },
            { value: "Anemo", label: "Anemo" },
            { value: "Geo", label: "Geo" },
            { value: "Electro", label: "Electro" },
            { value: "Dendro", label: "Dendro" },
            { value: "Hydro", label: "Hydro" },
            { value: "Pyro", label: "Pyro" },
            { value: "Cryo", label: "Cryo" },
        ],
        Circlet: [
            { value: "%HP", label: "%HP" },
            { value: "%ATK", label: "%ATK" },
            { value: "%DEF", label: "%DEF" },
            { value: "EM", label: "EM" },
            { value: "Crit Rate", label: "Crit Rate" },
            { value: "Crit DMG", label: "Crit DMG" },
            { value: "Healing", label: "Healing" },
        ],
    },
    allSubstats: ["HP", "%HP", "ATK", "%ATK", "DEF", "%DEF", "ER", "EM", "Crit Rate", "Crit DMG"],
    scores: ["Complete trash", "Trash", "Usable", "Good", "Excellent", "Marvelous", "Unknown"],
    sources: ["Domain farming", "Bosses", "Strongbox", "Spiral Abyss"],
    artifactSets: [
        "Archaic Petra",
        "Blizzard Strayer",
        "Bloodstained Chivalry",
        "Crimson Witch of Flames",
        "Deepwood Memories",
        "Desert Pavilion Chronicle",
        "Echoes of an Offering",
        "Emblem of Severed Fate",
        "Flower of Paradise Lost",
        "Fragment of Harmonic Whimsy",
        "Gilded Dreams",
        "Gladiator's Finale",
        "Golden Troupe",
        "Heart of Depth",
        "Husk of Opulent Dreams",
        "Lavawalker",
        "Maiden Beloved",
        "Marechaussee Hunter",
        "Nighttime of Whispers in the Echoing Woods",
        "Noblesse Oblige",
        "Nymph's Dream",
        "Obsidian Codex",
        "Ocean-Hued Clam",
        "Pale Flame",
        "Retracing Bolide",
        "Scroll of the Hero of Cinder City",
        "Shimenawa's Reminiscence",
        "Song of Days Past",
        "Tenacity of the Millelith",
        "Thundering Fury",
        "Thundersoother",
        "Unfinished Reverie",
        "Vermillion Hereafter",
        "Viridescent Venerer",
        "Vourukasha's Glow",
        "Wanderer's Troupe"
      ],
  };
  
  export { apiConfig, artifactConfig };